type Row = Record<string, unknown>;

function download(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportCSV(rows: Row[], filename = 'costpilot-export.csv') {
  if (rows.length === 0) {
    download(filename, '', 'text/csv');
    return;
  }
  const headers = Object.keys(rows[0]);
  const escape = (v: unknown) => {
    const s = v == null ? '' : String(v);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const csv = [
    headers.join(','),
    ...rows.map((r) => headers.map((h) => escape(r[h])).join(',')),
  ].join('\n');
  download(filename, csv, 'text/csv;charset=utf-8;');
}

export function exportExcel(rows: Row[], filename = 'costpilot-export.xls') {
  if (rows.length === 0) return;
  const headers = Object.keys(rows[0]);
  const tableRows = rows
    .map(
      (r) =>
        `<tr>${headers
          .map((h) => `<td style="border:1px solid #ccc;padding:6px">${String(r[h] ?? '')}</td>`)
          .join('')}</tr>`,
    )
    .join('');
  const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"></head><body><table style="border-collapse:collapse;font-family:sans-serif"><thead><tr>${headers
    .map((h) => `<th style="border:1px solid #ccc;padding:6px;background:#f3f4f6;text-align:left">${h}</th>`)
    .join('')}</tr></thead><tbody>${tableRows}</tbody></table></body></html>`;
  download(filename, html, 'application/vnd.ms-excel');
}

export function exportPDF(title: string, bodyHTML: string, filename = 'costpilot-report.pdf') {
  const win = window.open('', '_blank');
  if (!win) {
    alert('Please allow pop-ups to export the PDF.');
    return;
  }
  win.document.write(`<!doctype html><html><head><title>${title}</title><style>
    @page { margin: 24mm; }
    body { font-family: Inter, system-ui, sans-serif; color: #111; line-height: 1.5; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    h2 { font-size: 16px; margin-top: 24px; color: #2563eb; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 12px; }
    th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
    th { background: #f3f4f6; }
    .stat { display: inline-block; margin-right: 24px; }
    .stat .v { font-size: 20px; font-weight: 700; }
    .stat .l { font-size: 11px; color: #666; text-transform: uppercase; }
    .footer { margin-top: 32px; font-size: 11px; color: #888; border-top: 1px solid #eee; padding-top: 8px; }
  </style></head><body>${bodyHTML}<div class="footer">Generated by CostPilot AI · ${new Date().toLocaleString()}</div></body></html>`);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
}

export function downloadText(filename: string, content: string, mime = 'text/plain') {
  download(filename, content, mime);
}
